name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Clean and get dependencies
      - name: Clean and Get Dependencies
        run: |
          flutter clean
          flutter pub get

      # Setup iOS build
      - name: iOS Build Setup
        run: |
          cd ios
          rm -rf Pods/
          rm -f Podfile.lock
          pod cache clean --all
          pod repo update
          flutter precache --ios
          pod install --repo-update
          cd ..

      # Build iOS
      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r app.ipa Payload
          cd ../../..

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos/app.ipa
