name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Clean Flutter
        run: |
          flutter clean
          flutter pub get

      # Update Podfile
      - name: Update Podfile
        run: |
          cd ios
          echo "platform :ios, '15.5'
          
          target 'Runner' do
            use_frameworks!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
            
            target 'RunnerTests' do
              inherit! :search_paths
            end
          end
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
              end
            end
          end" > Podfile
          cd ..

      # Clean and reinstall CocoaPods
      - name: Clean and update CocoaPods
        run: |
          cd ios
          rm -rf Pods/
          rm -f Podfile.lock
          pod cache clean --all
          pod repo update
          pod install --repo-update
          cd ..

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
